# Generated by Django 2.2.5 on 2019-09-25 19:18

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_charfield_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('DELETED', 'DELETED')], default=blog.models.PostStatus('DRAFT'), max_length=255),
        ),
    ]
